#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 10
#define NKRO_DEFAULT_ON true
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_TIMEOUT 1200000     // 20 minutes (20 * 60 * 1000ms)
    #define RGB_MATRIX_SLEEP
#endif
